// Global game variables
        let gameSeq = []; // Stores the sequence generated by the game
        let userSeq = []; // Stores the sequence entered by the user
        let btns = ["red", "yellow", "green", "purple"]; // Array of button colors

        let started = false; // Flag to check if the game has started
        let level = 0; // Current game level
        let highScore = localStorage.getItem('simonSaysHighScore') ? parseInt(localStorage.getItem('simonSaysHighScore')) : 0; // High score from local storage

        // DOM elements
        let h2 = document.querySelector("#game-status");
        let highScoreDisplay = document.querySelector("#high-score-display");
        let allBtns = document.querySelectorAll(".btn");
        let messageBoxOverlay = document.getElementById("messageBoxOverlay");
        let messageBoxTitle = document.getElementById("messageBoxTitle");
        let messageBoxText = document.getElementById("messageBoxText");
        let messageBoxButton = document.getElementById("messageBoxButton");
        let getMemoryTipBtn = document.getElementById("getMemoryTipBtn"); 
        let getGameAnalysisBtn = document.getElementById("getGameAnalysisBtn"); 

        
        highScoreDisplay.innerText = highScore;

        
        function showMessage(title, message, showApiButtons = false) {
            messageBoxTitle.innerHTML = title; // Use innerHTML to support bold tag
            messageBoxText.innerHTML = message; // Use innerHTML to support bold tag
            messageBoxOverlay.classList.add("show");
            if (showApiButtons) {
                getMemoryTipBtn.style.display = "block"; // Show the Memory Tip button
                getGameAnalysisBtn.style.display = "block"; // Show the Game Analysis button
            } else {
                getMemoryTipBtn.style.display = "none"; // Hide it by default
                getGameAnalysisBtn.style.display = "none"; // Hide it by default
            }
        }

       
        function hideMessageBox() {
            messageBoxOverlay.classList.remove("show");
            getMemoryTipBtn.style.display = "none"; // Ensure it's hidden when box closes
            getGameAnalysisBtn.style.display = "none"; // Ensure it's hidden when box closes
        }

       
        messageBoxButton.addEventListener("click", hideMessageBox);

       
        getMemoryTipBtn.addEventListener("click", async function() {
            messageBoxText.innerHTML = "Fetching a memory tip... Please wait."; // Loading indicator
            this.disabled = true; // Disable button during fetch
            getGameAnalysisBtn.disabled = true; // Also disable the other API button

            try {
                let chatHistory = [];
                const prompt = "Provide a short, encouraging, and actionable memory improvement tip or a fun fact about how memory works. Keep it concise, around 1-2 sentences.";
                chatHistory.push({ role: "user", parts: [{ text: prompt }] });
                const payload = { contents: chatHistory };
                
               
                const apiUrl = ``;

                const response = await fetch(apiUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload)
                });

                const result = await response.json();

                if (result.candidates && result.candidates.length > 0 &&
                    result.candidates[0].content && result.candidates[0].content.parts &&
                    result.candidates[0].content.parts.length > 0) {
                    const text = result.candidates[0].content.parts[0].text;
                    messageBoxText.innerHTML = text; // Display the memory tip
                } else {
                    messageBoxText.innerHTML = "Failed to get a memory tip. Please try again.";
                }
            } catch (error) {
                console.error("Error fetching memory tip:", error);
                messageBoxText.innerHTML = "An error occurred while fetching the memory tip.";
            } finally {
                this.disabled = false; // Re-enable button
                getGameAnalysisBtn.disabled = false; // Re-enable the other API button
            }
        });

        // Event listener for the new "Game Analysis" button
        getGameAnalysisBtn.addEventListener("click", async function() {
            messageBoxText.innerHTML = "Analyzing your game... Please wait."; // Loading indicator
            this.disabled = true; // Disable button during fetch
            getMemoryTipBtn.disabled = true; // Also disable the other API button

            try {
                let chatHistory = [];
                const score = level - 1; // Get the final score
                const prompt = `The player's score in Simon Says was ${score}. Provide a short, encouraging, and light-hearted analysis of their performance. Suggest a positive outlook or a simple tip for next time. Keep it around 2-3 sentences.`;
                chatHistory.push({ role: "user", parts: [{ text: prompt }] });
                const payload = { contents: chatHistory };
               
                const apiUrl = ``;

                const response = await fetch(apiUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload)
                });

                const result = await response.json();

                if (result.candidates && result.candidates.length > 0 &&
                    result.candidates[0].content && result.candidates[0].content.parts &&
                    result.candidates[0].content.parts.length > 0) {
                    const text = result.candidates[0].content.parts[0].text;
                    messageBoxText.innerHTML = text; // Display the game analysis
                } else {
                    messageBoxText.innerHTML = "Failed to get game analysis. Please try again.";
                }
            } catch (error) {
                console.error("Error fetching game analysis:", error);
                messageBoxText.innerHTML = "An error occurred while fetching game analysis.";
            } finally {
                this.disabled = false; 
                getMemoryTipBtn.disabled = false; 
            }
        });


        // Event listener to start the game on any key press
    //     document.addEventListener("keypress", function(e) {
    //            if (
    //     !started &&
    //     e.target.tagName !== "INPUT" &&
    //     e.target.tagName !== "TEXTAREA"
    // ) {
    //     started = true;
    //     levelUp();
    // }

            // if (!started) {
            //     console.log("Game is started");
            //     started = true;
            //     levelUp();
            // }
    //    });

// function startGame() {
//     if (!started) {
//         started = true;
//         levelUp();
//     }
// }

// // Desktop support
// document.addEventListener("keypress", startGame);

// // Mobile support
// document.addEventListener("touchstart", startGame, { once: true });


        // Function to flash a button (game's turn)
        function gameFlash(btn) {
            btn.classList.add("flash");
            setTimeout(function () {
                btn.classList.remove("flash");
            }, 250);
        }

        // Function to flash a button (user's turn)
        function userFlash(btn) {
            btn.classList.add("userflash");
            setTimeout(function () {
                btn.classList.remove("userflash");
            }, 250);
        }

        // Function to increment level, generate next sequence, and flash buttons
        function levelUp() {
            userSeq = []; // Reset user sequence for the new level
            level++; // Increment game level
            h2.innerText = `Level ${level}`; // Update level display

            // Generate a random button to add to the game sequence
            let randIdx = Math.floor(Math.random() * 4); // Corrected Math.random() * 4 to cover all 4 buttons
            let randColor = btns[randIdx];
            let randBtn = document.querySelector(`.${randColor}`);

            gameSeq.push(randColor);
            console.log("Game Sequence:", gameSeq);
            gameFlash(randBtn);
        }

       

        // Function to handle user button clicks
        function btnPress() {
            let btn = this;
            userFlash(btn);
            let userColor = btn.getAttribute("id"); // Declared userColor with 'let'
            userSeq.push(userColor);
            checkAns(userSeq.length - 1);
        }

        // Add click event listeners to all game buttons
        for (let btn of allBtns) {
            btn.addEventListener("click", btnPress);
        }

        // Function to reset the game state
    function resetGame() {
    started = false;
    gameSeq = [];
    userSeq = [];
    level = 0;

    nameOverlay.style.display = "flex";
    document.body.classList.add("blur-bg");

    playerNameInput.value = "";

    h2.innerText = "Enter your name and press Start Game";
}
        // Name overlay elements
const nameOverlay = document.getElementById("nameOverlay");
const startGameBtn = document.getElementById("startGameBtn");
const playerNameInput = document.getElementById("playerNameInput");

// Leaderboard overlay elements
const leaderboardOverlay = document.getElementById("leaderboardOverlay");
const leaderboardList = document.getElementById("leaderboardList");
const closeLeaderboardBtn = document.getElementById("closeLeaderboardBtn");

let playerName = ""; // Will hold player's name

// Show name input overlay on initial load
window.addEventListener("DOMContentLoaded", () => {
    nameOverlay.style.display = "flex"; // Show overlay
    document.body.classList.add("blur-bg");
});

// Start game on name submission
startGameBtn.addEventListener("click", () => {
    alert("Start button clicked"); // TEST

    const name = playerNameInput.value.trim();

    if (name) {
        playerName = name;

        nameOverlay.style.display = "none";
        document.body.classList.remove("blur-bg");

        started = true;

        console.log("Starting game...");
        alert("Game Starting");

        levelUp();
    } else {
        alert("Please enter your name!");
    }
});



// startGameBtn.addEventListener("click", () => {
//     const name = playerNameInput.value.trim();

//     if (name) {
//         playerName = name;
//         nameOverlay.style.display = "none";
//         document.body.classList.remove("blur-bg");

//         // Start immediately
//         started = true;
//         levelUp();
//     } else {
//         alert("Please enter your name to start the game!");
//     }
// });

// Leaderboard Management
function updateLeaderboard(score) {
    let leaderboard = JSON.parse(localStorage.getItem("simonSaysLeaderboard")) || [];
    leaderboard.push({ name: playerName, score });
    leaderboard.sort((a, b) => b.score - a.score); // Sort descending
    leaderboard = leaderboard.slice(0, 5); // Keep top 5
    localStorage.setItem("simonSaysLeaderboard", JSON.stringify(leaderboard));
}

// Show leaderboard
function showLeaderboard() {
    leaderboardList.innerHTML = "";
    const leaderboard = JSON.parse(localStorage.getItem("simonSaysLeaderboard")) || [];
    if (leaderboard.length === 0) {
        leaderboardList.innerHTML = "<li>No scores yet. Be the first!</li>";
    } else {
        leaderboard.forEach((entry, index) => {
           const li = document.createElement("li");
li.textContent = `#${index + 1} ${entry.name} — ${entry.score}`;
            leaderboardList.appendChild(li);
        });
    }
    leaderboardOverlay.style.display = "flex";
}

// Close leaderboard overlay
closeLeaderboardBtn.addEventListener("click", () => {
    leaderboardOverlay.style.display = "none";
});

// Modify checkAns to update leaderboard
function checkAns(idx) {
    if (userSeq[idx] === gameSeq[idx]) {
        if (userSeq.length === gameSeq.length) {
            setTimeout(levelUp, 1000);
        }
    } else {
        const finalScore = level - 1;
        updateLeaderboard(finalScore); // ✅ Store player score
        showLeaderboard(); // ✅ Show leaderboard

        let message = `Game Over! Your score was <b>${finalScore}</b>.<br>`;
        if (finalScore > highScore) {
            highScore = finalScore;
            localStorage.setItem('simonSaysHighScore', highScore);
            highScoreDisplay.innerText = highScore;
            message = `Game Over! New High Score: <b>${highScore}</b>!<br>.`;
        }

        showMessage("Game Over!", message, true);
        h2.innerHTML = message;
        document.body.classList.add("gameover");
        setTimeout(() => document.body.classList.remove("gameover"), 150);
        resetGame();
    }
}
